### ISSUE TITLE
关于read_eeg_brainvision函数的问题

### ISSUE THREAD

**Issue by boom-R123** [ncclabsustech/Chinese_reading_task_eeg_processing#2]
老师您好，我在运行align_eeg_with_sentence.py时遇到了以下的错误：
![image](https://github.com/ncclabsustech/Chinese_reading_task_eeg_processing/assets/63643964/c8891266-7b5d-400a-920a-d4a6d7ee231a)
我查阅了一下资料，看起来是event_id中的key，value反了。因此，我将代码修改成了：
![image](https://github.com/ncclabsustech/Chinese_reading_task_eeg_processing/assets/63643964/66c618ef-fcaa-4c10-8950-c8321cca4fbb)
修改后，代码可以正常运行。请问这样修改是正确的吗？

**Comment by arnoliudaxia** [comment]
我也遇到了这个问题，但是按照作者的逻辑key value没有反。“解决”的方法是将annotations直接丢掉。（如果只需要数据没有影响）
```
    # annotations = mne.annotations_from_events(events, eeg.info['sfreq'], event_id)
    # eeg.set_annotations(annotations)
```
